import { Category, MemoryItem } from './types';

export const categories: Category[] = [
  {
    id: 'actors',
    name: 'Actors & Actresses',
    group: 'entertainment',
    icon: 'user',
    color: 'oklch(0.65 0.20 330)'
  },
  {
    id: 'movies',
    name: 'Movies',
    group: 'entertainment',
    icon: 'film',
    color: 'oklch(0.60 0.22 20)'
  },
  {
    id: 'musicians',
    name: 'Musicians',
    group: 'entertainment',
    icon: 'music-notes',
    color: 'oklch(0.68 0.20 280)'
  },
  {
    id: 'songs',
    name: 'Songs',
    group: 'entertainment',
    icon: 'microphone',
    color: 'oklch(0.70 0.18 140)'
  },
  {
    id: 'albums',
    name: 'Albums',
    group: 'entertainment',
    icon: 'disc',
    color: 'oklch(0.62 0.24 50)'
  },
  {
    id: 'cities',
    name: 'Cities',
    group: 'places',
    icon: 'buildings',
    color: 'oklch(0.55 0.18 240)'
  },
  {
    id: 'restaurants',
    name: 'Restaurants',
    group: 'places',
    icon: 'fork-knife',
    color: 'oklch(0.70 0.22 80)'
  },
  {
    id: 'streets',
    name: 'Streets',
    group: 'places',
    icon: 'signpost',
    color: 'oklch(0.58 0.15 220)'
  },
  {
    id: 'clothing-brands',
    name: 'Clothing Brands',
    group: 'brands',
    icon: 't-shirt',
    color: 'oklch(0.65 0.20 160)'
  },
  {
    id: 'shoe-brands',
    name: 'Shoe Brands',
    group: 'brands',
    icon: 'sneaker',
    color: 'oklch(0.60 0.22 200)'
  },
  {
    id: 'watch-brands',
    name: 'Watch Brands',
    group: 'brands',
    icon: 'watch',
    color: 'oklch(0.50 0.18 260)'
  },
  {
    id: 'perfume-brands',
    name: 'Perfume Brands',
    group: 'brands',
    icon: 'drop',
    color: 'oklch(0.72 0.18 320)'
  },
  {
    id: 'luxury-brands',
    name: 'Luxury Brands',
    group: 'brands',
    icon: 'diamond',
    color: 'oklch(0.58 0.20 40)'
  }
];

export const sampleMemoryItems: MemoryItem[] = [
  {
    id: '1',
    categoryId: 'actors',
    question: "¿Quién interpretó a Frida Kahlo en la película Frida?",
    questions: ["¿Quién interpretó a Frida Kahlo en el cine?", "¿Qué actriz mexicana fue nominada al Oscar?"],
    answer: 'Salma Hayek',
    answerType: 'single',
    hints: ["Actriz mexicana nominada al Oscar", "Su apellido significa 'tejedor' en árabe"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '2',
    categoryId: 'actors',
    question: "¿Quién es conocido como el ídolo del cine de oro mexicano?",
    questions: ["¿Qué actor mexicano cantaba y actuaba en los años 50?", "¿Quién murió en un accidente de aviación en 1957?"],
    answer: 'Pedro Infante',
    answerType: 'single',
    hints: ["Ídolo del cine de oro mexicano", "Cantante y actor de los años 50"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '3',
    categoryId: 'actors',
    question: "¿Quién interpretó a Che Guevara en Los Diarios de Motocicleta?",
    questions: ["¿Qué actor mexicano protagonizó Y Tu Mamá También?", "¿Quién actuó en Amores Perros?"],
    answer: 'Gael García Bernal',
    answerType: 'single',
    hints: ["Actor y director mexicano", "Protagonizó Amores Perros"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '4',
    categoryId: 'actors',
    question: "¿Quién ganó el Oscar por su papel en No Country for Old Men?",
    questions: ["¿Qué actor español trabajó con Almodóvar?", "¿Quién interpretó al villano en Skyfall?"],
    answer: 'Javier Bardem',
    answerType: 'single',
    hints: ["Actor español", "Interpretó al villano en Skyfall"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '5',
    categoryId: 'actors',
    question: "¿Quién interpretó a Zorro en la versión de 1998?",
    questions: ["¿Qué actor español protagonizó Dolor y Gloria?", "¿Quién trabajó en El Mariachi?"],
    answer: 'Antonio Banderas',
    answerType: 'single',
    hints: ["Actor español de Málaga", "Trabajó en varias películas de Almodóvar"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '6',
    categoryId: 'actors',
    question: "¿Quién protagonizó Volver junto a Penélope Cruz?",
    questions: ["¿Qué actriz española es conocida por sus papeles en películas de Almodóvar?"],
    answer: 'Carmen Maura',
    answerType: 'single',
    hints: ["Actriz española", "Protagonizó Mujeres al borde de un ataque de nervios"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '7',
    categoryId: 'actors',
    question: "¿Quién ganó el Oscar por Vicky Cristina Barcelona?",
    questions: ["¿Qué actriz española está casada con Javier Bardem?", "¿Quién trabajó con Pedro Almodóvar?"],
    answer: 'Penélope Cruz',
    answerType: 'single',
    hints: ["Primera actriz española en ganar un Oscar", "Trabajó con Pedro Almodóvar"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '8',
    categoryId: 'actors',
    question: "¿Quién interpretó a Amelie en la película francesa?",
    questions: ["¿Qué actriz francesa protagonizó El código Da Vinci?"],
    answer: 'Audrey Tautou',
    answerType: 'single',
    hints: ["Actriz francesa", "Rostro del perfume Chanel No. 5"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '9',
    categoryId: 'movies',
    question: "¿Qué película de Guillermo del Toro ganó el Oscar a Mejor Película?",
    questions: ["¿Qué película trata sobre una mujer muda y una criatura acuática?"],
    answer: 'La Forma del Agua',
    answerType: 'single',
    hints: ["Dirigida por Guillermo del Toro", "Ganó el Oscar en 2018"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '10',
    categoryId: 'movies',
    question: "¿Qué película española ganó el Oscar a Mejor Película Extranjera en 2000?",
    questions: ["¿Qué película de Almodóvar ganó el Oscar?"],
    answer: 'Todo Sobre Mi Madre',
    answerType: 'single',
    hints: ["Dirigida por Pedro Almodóvar", "Trata sobre maternidad y transgénero"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '11',
    categoryId: 'movies',
    question: "¿Qué película mexicana de Alfonso Cuarón ganó múltiples Oscars en 2019?",
    questions: ["¿Qué película en blanco y negro sobre una empleada doméstica?"],
    answer: 'Roma',
    answerType: 'single',
    hints: ["Dirigida por Alfonso Cuarón", "Filmada en blanco y negro"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '12',
    categoryId: 'movies',
    question: "¿Qué película de Almodóvar trata sobre dos mujeres y un crimen?",
    questions: ["¿En qué película Penélope Cruz canta?"],
    answer: 'Volver',
    answerType: 'single',
    hints: ["Protagonizada por Penélope Cruz", "Se desarrolla en La Mancha"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '13',
    categoryId: 'movies',
    question: "¿Qué película francesa cuenta la historia de una camarera peculiar?",
    questions: ["¿Qué película tiene escenas icónicas en Montmartre?"],
    answer: 'Amelie',
    answerType: 'single',
    hints: ["Protagonizada por Audrey Tautou", "Ambientada en París"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '14',
    categoryId: 'movies',
    question: "¿Qué película argentina ganó el Oscar a Mejor Película Extranjera en 2010?",
    questions: ["¿Qué thriller argentino trata sobre un crimen sin resolver?"],
    answer: 'El Secreto de Sus Ojos',
    answerType: 'single',
    hints: ["Dirigida por Juan José Campanella", "Thriller romántico"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '15',
    categoryId: 'movies',
    question: "¿Qué película española de 2006 se desarrolla durante la Guerra Civil?",
    questions: ["¿Qué película de Guillermo del Toro tiene un fauno?"],
    answer: 'El Laberinto del Fauno',
    answerType: 'single',
    hints: ["Dirigida por Guillermo del Toro", "Fantasía oscura"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '16',
    categoryId: 'movies',
    question: "¿Qué película mexicana de Iñárritu trata sobre tres historias entrelazadas?",
    questions: ["¿Qué película mexicana tiene un accidente de auto como eje central?"],
    answer: 'Amores Perros',
    answerType: 'single',
    hints: ["Dirigida por Alejandro González Iñárritu", "Gael García Bernal protagoniza"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '17',
    categoryId: 'musicians',
    question: "¿Quién es conocido como el Rey del Pop Latino?",
    questions: ["¿Quién cantó Livin' la Vida Loca?", "¿Qué cantante puertorriqueño fue parte de Menudo?"],
    answer: 'Ricky Martin',
    answerType: 'single',
    hints: ["Cantante puertorriqueño", "Fue miembro de Menudo"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '18',
    categoryId: 'musicians',
    question: "¿Quién es la Reina del Tex-Mex?",
    questions: ["¿Qué cantante fue asesinada en 1995?", "¿Quién cantó Bidi Bidi Bom Bom?"],
    answer: 'Selena Quintanilla',
    answerType: 'single',
    hints: ["Cantante tex-mex", "Asesinada en 1995"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '19',
    categoryId: 'musicians',
    question: "¿Quién cantó La Bamba?",
    questions: ["¿Qué músico mexicano-americano murió joven en un accidente?"],
    answer: 'Ritchie Valens',
    answerType: 'single',
    hints: ["Músico mexicano-americano", "Murió en accidente de avión"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '20',
    categoryId: 'musicians',
    question: "¿Quién es la cantante colombiana conocida mundialmente?",
    questions: ["¿Quién cantó Hips Don't Lie?", "¿Quién cantó Waka Waka?"],
    answer: 'Shakira',
    answerType: 'single',
    hints: ["Cantante colombiana", "Famosa por su baile de cadera"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '21',
    categoryId: 'musicians',
    question: "¿Quién cantó Bailando con Enrique Iglesias?",
    questions: ["¿Qué grupo cubano es famoso por la música de reggaeton?"],
    answer: 'Gente de Zona',
    answerType: 'single',
    hints: ["Grupo cubano", "Famosos por Bailando"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '22',
    categoryId: 'musicians',
    question: "¿Quién es el cantante español conocido como el Rey del Pop español?",
    questions: ["¿Quién cantó Bailar Pegados?"],
    answer: 'Sergio Dalma',
    answerType: 'single',
    hints: ["Cantante español", "Famoso por baladas románticas"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '23',
    categoryId: 'musicians',
    question: "¿Quién es el cantante puertorriqueño del trap latino?",
    questions: ["¿Quién cantó Soy Peor?", "¿Quién es conocido como el conejo malo?"],
    answer: 'Bad Bunny',
    answerType: 'single',
    hints: ["Cantante puertorriqueño", "Pionero del trap latino"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '24',
    categoryId: 'musicians',
    question: "¿Quién cantó Despacito?",
    questions: ["¿Qué cantante puertorriqueño es conocido mundialmente?"],
    answer: 'Luis Fonsi',
    answerType: 'single',
    hints: ["Cantante puertorriqueño", "Despacito fue un hit mundial"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '25',
    categoryId: 'songs',
    question: "¿Qué canción de Luis Fonsi se volvió viral mundialmente?",
    questions: ["¿Qué canción tiene la colaboración de Daddy Yankee?"],
    answer: 'Despacito',
    answerType: 'single',
    hints: ["Hit mundial de 2017", "Colaboración con Daddy Yankee"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '26',
    categoryId: 'songs',
    question: "¿Qué canción de Shakira se usó en el Mundial 2010?",
    questions: ["¿Qué canción dice 'This time for Africa'?"],
    answer: 'Waka Waka',
    answerType: 'single',
    hints: ["Canción del Mundial 2010", "Cantada por Shakira"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '27',
    categoryId: 'songs',
    question: "¿Qué canción de Maná habla sobre una mujer hermosa?",
    questions: ["¿Qué canción de Maná es un clásico del rock en español?"],
    answer: 'Mariposa Traicionera',
    answerType: 'single',
    hints: ["Banda mexicana Maná", "Habla sobre una mariposa"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '28',
    categoryId: 'songs',
    question: "¿Qué canción de Juanes habla de camisas negras?",
    questions: ["¿Qué hit de Juanes fue número uno en varios países?"],
    answer: 'La Camisa Negra',
    answerType: 'single',
    hints: ["Cantada por Juanes", "Habla sobre tristeza"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '29',
    categoryId: 'songs',
    question: "¿Qué canción de Enrique Iglesias habla sobre bailar?",
    questions: ["¿Qué canción tiene la colaboración de Gente de Zona?"],
    answer: 'Bailando',
    answerType: 'single',
    hints: ["Colaboración con Gente de Zona", "Hit de 2014"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '30',
    categoryId: 'songs',
    question: "¿Qué canción de Daddy Yankee se volvió un himno del reggaeton?",
    questions: ["¿Qué canción dice 'dale a tu cuerpo alegría'?"],
    answer: 'Gasolina',
    answerType: 'single',
    hints: ["Cantada por Daddy Yankee", "Himno del reggaeton"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '31',
    categoryId: 'songs',
    question: "¿Qué canción de Selena es su más icónica?",
    questions: ["¿Qué canción dice 'Bidi Bidi Bom Bom'?"],
    answer: 'Bidi Bidi Bom Bom',
    answerType: 'single',
    hints: ["Cantada por Selena", "Habla del corazón"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '32',
    categoryId: 'songs',
    question: "¿Qué canción de Carlos Vives habla sobre un río?",
    questions: ["¿Qué canción colombiana es un clásico del vallenato?"],
    answer: 'La Gota Fría',
    answerType: 'single',
    hints: ["Cantada por Carlos Vives", "Vallenato moderno"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '33',
    categoryId: 'albums',
    question: "¿Qué álbum de Shakira incluye Whenever, Wherever?",
    questions: ["¿Qué álbum marcó el crossover de Shakira al inglés?"],
    answer: 'Laundry Service',
    answerType: 'single',
    hints: ["Álbum de Shakira de 2001", "Primer álbum en inglés"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '34',
    categoryId: 'albums',
    question: "¿Qué álbum de Maná es considerado su obra maestra?",
    questions: ["¿Qué álbum incluye Rayando el Sol?"],
    answer: 'Falta Amor',
    answerType: 'single',
    hints: ["Álbum de Maná", "Incluye Rayando el Sol"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '35',
    categoryId: 'albums',
    question: "¿Qué álbum de Bad Bunny rompió récords en 2020?",
    questions: ["¿Qué álbum de Bad Bunny salió durante la pandemia?"],
    answer: 'YHLQMDLG',
    answerType: 'single',
    hints: ["Álbum de Bad Bunny de 2020", "Significa 'Yo Hago Lo Que Me Da La Gana'"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '36',
    categoryId: 'albums',
    question: "¿Qué álbum de Café Tacvba es considerado revolucionario?",
    questions: ["¿Qué álbum mexicano mezcla múltiples géneros?"],
    answer: 'Re',
    answerType: 'single',
    hints: ["Álbum de Café Tacvba", "Título de una sola sílaba"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '37',
    categoryId: 'albums',
    question: "¿Qué álbum de Juanes ganó múltiples Grammys?",
    questions: ["¿Qué álbum incluye A Dios le Pido?"],
    answer: 'Un Día Normal',
    answerType: 'single',
    hints: ["Álbum de Juanes", "Incluye A Dios le Pido"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '38',
    categoryId: 'albums',
    question: "¿Qué álbum de Soda Stereo es el más vendido?",
    questions: ["¿Qué álbum argentino incluye De Música Ligera?"],
    answer: 'Canción Animal',
    answerType: 'single',
    hints: ["Álbum de Soda Stereo", "Incluye De Música Ligera"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '39',
    categoryId: 'albums',
    question: "¿Qué álbum de Selena fue lanzado póstumamente?",
    questions: ["¿Qué álbum de Selena incluye Dreaming of You?"],
    answer: 'Dreaming of You',
    answerType: 'single',
    hints: ["Álbum póstumo de Selena", "Crossover al inglés"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '40',
    categoryId: 'albums',
    question: "¿Qué álbum de Rosalía fusiona flamenco y trap?",
    questions: ["¿Qué álbum español revolucionó la música en 2018?"],
    answer: 'El Mal Querer',
    answerType: 'single',
    hints: ["Álbum de Rosalía", "Mezcla flamenco y urbano"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '41',
    categoryId: 'cities',
    question: "¿Qué ciudad española tiene la Sagrada Familia?",
    questions: ["¿Qué ciudad tiene arquitectura de Gaudí?", "¿Qué ciudad tiene Las Ramblas?"],
    answer: 'Barcelona',
    answerType: 'single',
    hints: ["Ciudad española", "Capital de Cataluña"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '42',
    categoryId: 'cities',
    question: "¿Qué ciudad mexicana es famosa por el Día de Muertos?",
    questions: ["¿Qué ciudad tiene la Plaza del Zócalo?", "¿Cuál es la capital de México?"],
    answer: 'Ciudad de México',
    answerType: 'single',
    hints: ["Capital de México", "Una de las ciudades más grandes del mundo"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '43',
    categoryId: 'cities',
    question: "¿Qué ciudad argentina es conocida por el tango?",
    questions: ["¿Qué ciudad tiene el barrio La Boca?", "¿Cuál es la capital de Argentina?"],
    answer: 'Buenos Aires',
    answerType: 'single',
    hints: ["Capital de Argentina", "Cuna del tango"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '44',
    categoryId: 'cities',
    question: "¿Qué ciudad peruana tiene Machu Picchu cerca?",
    questions: ["¿Qué ciudad es la puerta de entrada a Machu Picchu?"],
    answer: 'Cusco',
    answerType: 'single',
    hints: ["Ciudad peruana", "Antigua capital inca"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '45',
    categoryId: 'cities',
    question: "¿Qué ciudad española tiene la Alhambra?",
    questions: ["¿Qué ciudad andaluza tiene arquitectura árabe?"],
    answer: 'Granada',
    answerType: 'single',
    hints: ["Ciudad española", "En Andalucía"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '46',
    categoryId: 'cities',
    question: "¿Qué ciudad colombiana es conocida por su clima primaveral?",
    questions: ["¿Qué ciudad colombiana es llamada la ciudad de la eterna primavera?"],
    answer: 'Medellín',
    answerType: 'single',
    hints: ["Ciudad colombiana", "Segunda ciudad más grande de Colombia"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '47',
    categoryId: 'cities',
    question: "¿Qué ciudad chilena es famosa por sus cerros coloridos?",
    questions: ["¿Qué ciudad portuaria chilena tiene funiculares?"],
    answer: 'Valparaíso',
    answerType: 'single',
    hints: ["Ciudad portuaria de Chile", "Patrimonio de la Humanidad"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '48',
    categoryId: 'cities',
    question: "¿Qué ciudad cubana es la capital?",
    questions: ["¿Qué ciudad tiene el Malecón?", "¿Qué ciudad tiene autos antiguos?"],
    answer: 'La Habana',
    answerType: 'single',
    hints: ["Capital de Cuba", "Famosa por sus autos clásicos"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '49',
    categoryId: 'restaurants',
    question: "¿Qué restaurante español tiene 3 estrellas Michelin en San Sebastián?",
    questions: ["¿Qué restaurante es dirigido por el chef Berasategui?"],
    answer: 'Martín Berasategui',
    answerType: 'single',
    hints: ["En San Sebastián", "Chef vasco con múltiples estrellas"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '50',
    categoryId: 'restaurants',
    question: "¿Qué restaurante español fue votado mejor del mundo?",
    questions: ["¿Qué restaurante catalán fue número uno?"],
    answer: 'El Celler de Can Roca',
    answerType: 'single',
    hints: ["En Girona", "Dirigido por los hermanos Roca"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '51',
    categoryId: 'restaurants',
    question: "¿Qué restaurante peruano es famoso por la cocina nikkei?",
    questions: ["¿Qué restaurante limeño mezcla cocina japonesa y peruana?"],
    answer: 'Maido',
    answerType: 'single',
    hints: ["En Lima", "Chef Mitsuharu Tsumura"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '52',
    categoryId: 'restaurants',
    question: "¿Qué restaurante mexicano tiene 3 estrellas Michelin?",
    questions: ["¿Qué restaurante de Enrique Olvera está en la CDMX?"],
    answer: 'Pujol',
    answerType: 'single',
    hints: ["En Ciudad de México", "Chef Enrique Olvera"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '53',
    categoryId: 'streets',
    question: "¿Qué avenida madrileña es famosa por sus tiendas?",
    questions: ["¿Qué calle de Madrid tiene la Puerta del Sol?"],
    answer: 'Gran Vía',
    answerType: 'single',
    hints: ["En Madrid", "Calle principal de compras"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '54',
    categoryId: 'streets',
    question: "¿Qué avenida de Buenos Aires es la más ancha del mundo?",
    questions: ["¿Qué avenida argentina tiene 16 carriles?"],
    answer: 'Avenida 9 de Julio',
    answerType: 'single',
    hints: ["En Buenos Aires", "La avenida más ancha del mundo"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '55',
    categoryId: 'streets',
    question: "¿Qué avenida de Barcelona va desde la Plaza Cataluña al mar?",
    questions: ["¿Qué calle famosa de Barcelona tiene artistas callejeros?"],
    answer: 'Las Ramblas',
    answerType: 'single',
    hints: ["En Barcelona", "Llena de turistas y artistas"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '56',
    categoryId: 'streets',
    question: "¿Qué calle de La Habana es famosa por la música?",
    questions: ["¿Qué calle cubana tiene bares con música en vivo?"],
    answer: 'Calle Obispo',
    answerType: 'single',
    hints: ["En La Habana Vieja", "Llena de vida y música"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '57',
    categoryId: 'clothing-brands',
    question: "¿Qué marca española es conocida por sus bolsos?",
    questions: ["¿Qué marca de moda rápida es de España?"],
    answer: 'Zara',
    answerType: 'single',
    hints: ["Marca española", "Parte del grupo Inditex"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '58',
    categoryId: 'clothing-brands',
    question: "¿Qué marca española tiene un oso como logo?",
    questions: ["¿Qué marca de ropa infantil es española?"],
    answer: 'Tous',
    answerType: 'single',
    hints: ["Marca española de joyería", "Logo de oso"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '59',
    categoryId: 'clothing-brands',
    question: "¿Qué marca española compite con Zara?",
    questions: ["¿Qué marca de Inditex es más elegante?"],
    answer: 'Massimo Dutti',
    answerType: 'single',
    hints: ["Parte de Inditex", "Ropa más formal que Zara"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '60',
    categoryId: 'clothing-brands',
    question: "¿Qué marca española es conocida por ropa de bebés?",
    questions: ["¿Qué marca española tiene ropa infantil?"],
    answer: 'Mayoral',
    answerType: 'single',
    hints: ["Marca española", "Especializada en niños"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '61',
    categoryId: 'shoe-brands',
    question: "¿Qué marca española hace alpargatas?",
    questions: ["¿Qué marca de calzado casual es de España?"],
    answer: 'Castañer',
    answerType: 'single',
    hints: ["Marca española", "Famosa por alpargatas"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '62',
    categoryId: 'shoe-brands',
    question: "¿Qué marca española de zapatos es de lujo?",
    questions: ["¿Qué marca de zapatos tiene tiendas en las mejores calles?"],
    answer: 'Camper',
    answerType: 'single',
    hints: ["Marca española", "Zapatos casuales y cómodos"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '63',
    categoryId: 'shoe-brands',
    question: "¿Qué marca mexicana hace huaraches?",
    questions: ["¿Qué calzado tradicional mexicano es famoso?"],
    answer: 'Huaraches Mexicanos',
    answerType: 'single',
    hints: ["Calzado tradicional", "Sandalias tejidas"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '64',
    categoryId: 'shoe-brands',
    question: "¿Qué marca argentina hace zapatos de cuero?",
    questions: ["¿Qué marca de Buenos Aires es famosa por el cuero?"],
    answer: 'Mishka',
    answerType: 'single',
    hints: ["Marca argentina", "Zapatos de cuero"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '65',
    categoryId: 'watch-brands',
    question: "¿Qué marca española hace relojes de diseño?",
    questions: ["¿Qué marca de Barcelona hace relojes minimalistas?"],
    answer: 'Komono',
    answerType: 'single',
    hints: ["Marca de Barcelona", "Diseño minimalista"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '66',
    categoryId: 'watch-brands',
    question: "¿Qué marca mexicana hace relojes artesanales?",
    questions: ["¿Qué marca de relojes es de México?"],
    answer: 'Nixon',
    answerType: 'single',
    hints: ["Marca popular en México", "Relojes casuales"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '67',
    categoryId: 'perfume-brands',
    question: "¿Qué marca española hace perfumes de nicho?",
    questions: ["¿Qué marca de perfumes es de Barcelona?"],
    answer: 'Carner Barcelona',
    answerType: 'single',
    hints: ["Marca de Barcelona", "Perfumes de nicho"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '68',
    categoryId: 'perfume-brands',
    question: "¿Qué marca española hace agua de colonia?",
    questions: ["¿Qué perfume español es tradicional?"],
    answer: 'Agua de Colonia Concentrada',
    answerType: 'single',
    hints: ["Perfume español tradicional", "En botella verde"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '69',
    categoryId: 'perfume-brands',
    question: "¿Qué marca mexicana hace perfumes?",
    questions: ["¿Qué fragancia mexicana es famosa?"],
    answer: 'Pinaud Clubman',
    answerType: 'single',
    hints: ["Popular en México", "Aftershave clásico"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '70',
    categoryId: 'luxury-brands',
    question: "¿Qué marca española es conocida por el cuero?",
    questions: ["¿Qué marca de lujo española hace bolsos?"],
    answer: 'Loewe',
    answerType: 'single',
    hints: ["Marca española", "Famosa por bolsos de cuero"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '71',
    categoryId: 'luxury-brands',
    question: "¿Qué marca española hace joyería de lujo?",
    questions: ["¿Qué joyería española tiene tiendas en todo el mundo?"],
    answer: 'Carrera y Carrera',
    answerType: 'single',
    hints: ["Joyería española", "Diseños escultóricos"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '72',
    categoryId: 'luxury-brands',
    question: "¿Qué marca argentina es conocida por el cuero?",
    questions: ["¿Qué marca de Buenos Aires hace productos de cuero?"],
    answer: 'Prüne',
    answerType: 'single',
    hints: ["Marca argentina", "Bolsos y zapatos de cuero"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '73',
    categoryId: 'luxury-brands',
    question: "¿Qué marca mexicana es conocida por la plata?",
    questions: ["¿Qué joyería mexicana usa plata de Taxco?"],
    answer: 'Tane',
    answerType: 'single',
    hints: ["Joyería mexicana", "Trabaja con plata"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '74',
    categoryId: 'musicians',
    question: "¿Quién es el tenor español más famoso?",
    questions: ["¿Quién cantó con los Tres Tenores?", "¿Quién es de Barcelona y canta ópera?"],
    answer: 'Plácido Domingo',
    answerType: 'single',
    hints: ["Tenor español", "Uno de los Tres Tenores"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '75',
    categoryId: 'musicians',
    question: "¿Quién cantó Bésame Mucho?",
    questions: ["¿Quién es la cantante mexicana de boleros?"],
    answer: 'Consuelo Velázquez',
    answerType: 'single',
    hints: ["Compositora mexicana", "Escribió Bésame Mucho"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '76',
    categoryId: 'songs',
    question: "¿Qué canción de Héctor Lavoe es un clásico de la salsa?",
    questions: ["¿Qué canción dice 'Juanito Alimaña'?"],
    answer: 'El Cantante',
    answerType: 'single',
    hints: ["Cantada por Héctor Lavoe", "Clásico de salsa"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '77',
    categoryId: 'songs',
    question: "¿Qué canción de Celia Cruz es su más famosa?",
    questions: ["¿Qué canción dice 'la vida es un carnaval'?"],
    answer: 'La Vida Es Un Carnaval',
    answerType: 'single',
    hints: ["Cantada por Celia Cruz", "Mensaje positivo"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '78',
    categoryId: 'songs',
    question: "¿Qué canción de Rubén Blades habla sobre Pedro Navaja?",
    questions: ["¿Qué canción de salsa cuenta una historia?"],
    answer: 'Pedro Navaja',
    answerType: 'single',
    hints: ["Cantada por Rubén Blades", "Narra una historia"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '79',
    categoryId: 'albums',
    question: "¿Qué álbum de Héroe s Silencio marcó el rock español?",
    questions: ["¿Qué álbum incluye Entre Dos Tierras?"],
    answer: 'Senderos de Traición',
    answerType: 'single',
    hints: ["Álbum de Héroes del Silencio", "Rock español de los 90"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '80',
    categoryId: 'albums',
    question: "¿Qué álbum de Mecano fue el más vendido?",
    questions: ["¿Qué álbum español incluye Hijo de la Luna?"],
    answer: 'Descanso Dominical',
    answerType: 'single',
    hints: ["Álbum de Mecano", "Pop español de los 80"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '81',
    categoryId: 'cities',
    question: "¿Qué ciudad española tiene la Mezquita?",
    questions: ["¿Qué ciudad andaluza tiene arquitectura musulmana?"],
    answer: 'Córdoba',
    answerType: 'single',
    hints: ["En Andalucía", "Famosa por la Mezquita-Catedral"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '82',
    categoryId: 'cities',
    question: "¿Qué ciudad mexicana es famosa por mariachis?",
    questions: ["¿Qué ciudad es la capital de Jalisco?"],
    answer: 'Guadalajara',
    answerType: 'single',
    hints: ["En Jalisco", "Cuna del mariachi"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '83',
    categoryId: 'cities',
    question: "¿Qué ciudad española es famosa por la Tomatina?",
    questions: ["¿En qué ciudad se tiran tomates en agosto?"],
    answer: 'Buñol',
    answerType: 'single',
    hints: ["Cerca de Valencia", "Festival de la Tomatina"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '84',
    categoryId: 'cities',
    question: "¿Qué ciudad venezolana es la capital?",
    questions: ["¿Qué ciudad tiene el Ávila?"],
    answer: 'Caracas',
    answerType: 'single',
    hints: ["Capital de Venezuela", "Al pie del Ávila"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '85',
    categoryId: 'movies',
    question: "¿Qué película española trata sobre un hotel en los años 40?",
    questions: ["¿Qué película de Amenábar tiene fantasmas?"],
    answer: 'Los Otros',
    answerType: 'single',
    hints: ["Dirigida por Alejandro Amenábar", "Protagonizada por Nicole Kidman"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '86',
    categoryId: 'movies',
    question: "¿Qué película chilena fue nominada al Oscar?",
    questions: ["¿Qué película trata sobre Pinochet?"],
    answer: 'No',
    answerType: 'single',
    hints: ["Dirigida por Pablo Larraín", "Sobre el plebiscito de 1988"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '87',
    categoryId: 'movies',
    question: "¿Qué película mexicana trata sobre luchadores?",
    questions: ["¿Qué película de Jack Black es sobre lucha libre?"],
    answer: 'Nacho Libre',
    answerType: 'single',
    hints: ["Protagonizada por Jack Black", "Sobre lucha libre mexicana"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '88',
    categoryId: 'movies',
    question: "¿Qué película animada mexicana trata sobre el Día de Muertos?",
    questions: ["¿Qué película tiene un niño que quiere ser músico?"],
    answer: 'Coco',
    answerType: 'single',
    hints: ["Película de Pixar", "Sobre el Día de Muertos"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '89',
    categoryId: 'actors',
    question: "¿Quién es el actor español que salió en Piratas del Caribe?",
    questions: ["¿Qué actor español interpretó al Che Guevara?"],
    answer: 'Benicio del Toro',
    answerType: 'single',
    hints: ["Actor puertorriqueño", "Ganó un Oscar"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '90',
    categoryId: 'musicians',
    question: "¿Quién es conocido como el Potrillo?",
    questions: ["¿Quién es el hijo de Vicente Fernández?"],
    answer: 'Alejandro Fernández',
    answerType: 'single',
    hints: ["Cantante mexicano", "Hijo de Vicente Fernández"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '91',
    categoryId: 'musicians',
    question: "¿Quién es conocido como el Rey de la Música Ranchera?",
    questions: ["¿Quién cantó Volver Volver?"],
    answer: 'Vicente Fernández',
    answerType: 'single',
    hints: ["Cantante mexicano", "Ícono de la música ranchera"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '92',
    categoryId: 'songs',
    question: "¿Qué canción de Juan Gabriel es la más famosa?",
    questions: ["¿Qué canción dice 'amor eterno'?"],
    answer: 'Amor Eterno',
    answerType: 'single',
    hints: ["Cantada por Juan Gabriel", "Balada romántica"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '93',
    categoryId: 'songs',
    question: "¿Qué canción de Mecano habla de un hijo de la luna?",
    questions: ["¿Qué canción española narra una leyenda?"],
    answer: 'Hijo de la Luna',
    answerType: 'single',
    hints: ["Cantada por Mecano", "Narra una historia trágica"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '94',
    categoryId: 'restaurants',
    question: "¿Qué restaurante peruano de Gastón Acurio es famoso?",
    questions: ["¿Qué restaurante limeño revolucionó la cocina peruana?"],
    answer: 'Astrid y Gastón',
    answerType: 'single',
    hints: ["En Lima", "Chef Gastón Acurio"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '95',
    categoryId: 'restaurants',
    question: "¿Qué restaurante argentino es famoso por las parrillas?",
    questions: ["¿Qué parrilla de Buenos Aires es legendaria?"],
    answer: 'Don Julio',
    answerType: 'single',
    hints: ["En Buenos Aires", "Famoso por carne a la parrilla"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '96',
    categoryId: 'streets',
    question: "¿Qué calle de México tiene embajadas y restaurantes?",
    questions: ["¿Qué avenida de la CDMX es famosa?"],
    answer: 'Paseo de la Reforma',
    answerType: 'single',
    hints: ["En Ciudad de México", "Avenida principal"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '97',
    categoryId: 'albums',
    question: "¿Qué álbum de Caifanes marcó el rock mexicano?",
    questions: ["¿Qué álbum incluye La Célula Que Explota?"],
    answer: 'El Diablito',
    answerType: 'single',
    hints: ["Álbum de Caifanes", "Rock mexicano de los 90"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '98',
    categoryId: 'cities',
    question: "¿Qué ciudad brasileña es famosa por el carnaval?",
    questions: ["¿Qué ciudad tiene el Cristo Redentor?"],
    answer: 'Río de Janeiro',
    answerType: 'single',
    hints: ["En Brasil", "Famosa por el carnaval"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '99',
    categoryId: 'movies',
    question: "¿Qué película española ganó el Oscar en 2022?",
    questions: ["¿Qué película de Almodóvar ganó el Oscar?"],
    answer: 'Madres Paralelas',
    answerType: 'single',
    hints: ["Dirigida por Almodóvar", "Protagonizada por Penélope Cruz"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '100',
    categoryId: 'musicians',
    question: "¿Quién es la Reina de la Salsa?",
    questions: ["¿Quién cantó Guantanamera?"],
    answer: 'Celia Cruz',
    answerType: 'single',
    hints: ["Cantante cubana", "Reina de la Salsa"],
    isCustom: false,
    difficulty: 'easy'
  }
];
