import { Category, MemoryItem } from './types';

export const categories: Category[] = [
  {
    id: 'actors',
    name: 'Actors & Actresses',
    group: 'entertainment',
    icon: 'user',
    color: 'oklch(0.65 0.20 330)'
  },
  {
    id: 'movies',
    name: 'Movies',
    group: 'entertainment',
    icon: 'film',
    color: 'oklch(0.60 0.22 20)'
  },
  {
    id: 'musicians',
    name: 'Musicians',
    group: 'entertainment',
    icon: 'music-notes',
    color: 'oklch(0.68 0.20 280)'
  },
  {
    id: 'songs',
    name: 'Songs',
    group: 'entertainment',
    icon: 'microphone',
    color: 'oklch(0.70 0.18 140)'
  },
  {
    id: 'albums',
    name: 'Albums',
    group: 'entertainment',
    icon: 'disc',
    color: 'oklch(0.62 0.24 50)'
  },
  {
    id: 'cities',
    name: 'Cities',
    group: 'places',
    icon: 'buildings',
    color: 'oklch(0.55 0.18 240)'
  },
  {
    id: 'restaurants',
    name: 'Restaurants',
    group: 'places',
    icon: 'fork-knife',
    color: 'oklch(0.70 0.22 80)'
  },
  {
    id: 'streets',
    name: 'Streets',
    group: 'places',
    icon: 'signpost',
    color: 'oklch(0.58 0.15 220)'
  },
  {
    id: 'clothing-brands',
    name: 'Clothing Brands',
    group: 'brands',
    icon: 't-shirt',
    color: 'oklch(0.65 0.20 160)'
  },
  {
    id: 'shoe-brands',
    name: 'Shoe Brands',
    group: 'brands',
    icon: 'sneaker',
    color: 'oklch(0.60 0.22 200)'
  },
  {
    id: 'watch-brands',
    name: 'Watch Brands',
    group: 'brands',
    icon: 'watch',
    color: 'oklch(0.50 0.18 260)'
  },
  {
    id: 'perfume-brands',
    name: 'Perfume Brands',
    group: 'brands',
    icon: 'drop',
    color: 'oklch(0.72 0.18 320)'
  },
  {
    id: 'luxury-brands',
    name: 'Luxury Brands',
    group: 'brands',
    icon: 'diamond',
    color: 'oklch(0.58 0.20 40)'
  }
];

export const sampleMemoryItems: MemoryItem[] = [
  {
    id: '1',
    categoryId: 'actors',
    question: "Who played Iron Man in the Marvel Cinematic Universe?",
    questions: ["Who is the actor behind Tony Stark?", "Which actor started the MCU?"],
    answer: 'Robert Downey Jr.',
    answerType: 'single',
    hints: ["Known for his comeback story", "Has the initials RDJ"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '2',
    categoryId: 'actors',
    question: "Who played the Joker in The Dark Knight?",
    questions: ["Which actor gave a legendary performance in a Batman film?", "Who posthumously won an Oscar for playing a villain?"],
    answer: 'Heath Ledger',
    answerType: 'single',
    hints: ["Australian actor", "Tragically died before the film's release"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '3',
    categoryId: 'actors',
    question: "Who starred as Jack in Titanic?",
    questions: ["Which actor became a global heartthrob in 1997?", "Who finally won his first Oscar for The Revenant?"],
    answer: 'Leonardo DiCaprio',
    answerType: 'single',
    hints: ["Also famous for environmental activism", "Worked with Martin Scorsese many times"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '4',
    categoryId: 'actors',
    question: "Who played Forrest Gump?",
    questions: ["Which actor said 'Life is like a box of chocolates'?", "Who voiced Woody in Toy Story?"],
    answer: 'Tom Hanks',
    answerType: 'single',
    hints: ["Known as one of Hollywood's nicest actors", "Won back-to-back Oscars in the 90s"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '5',
    categoryId: 'actors',
    question: "Who played Hermione Granger in Harry Potter?",
    questions: ["Which British actress became a UN Women Goodwill Ambassador?", "Who launched the HeForShe campaign?"],
    answer: 'Emma Watson',
    answerType: 'single',
    hints: ["Known for activism on women's rights", "First name sounds like a popular novel"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '6',
    categoryId: 'actors',
    question: "Who played Black Widow in the MCU?",
    questions: ["Which actress has been in multiple Marvel films as Natasha Romanoff?", "Who starred in Lucy and Ghost in the Shell?"],
    answer: 'Scarlett Johansson',
    answerType: 'single',
    hints: ["One of the highest-paid actresses", "First name is a shade of red"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '7',
    categoryId: 'actors',
    question: "Who played Wolverine in the X-Men franchise?",
    questions: ["Which Australian actor is known for musical theater and superhero roles?", "Who starred in The Greatest Showman?"],
    answer: 'Hugh Jackman',
    answerType: 'single',
    hints: ["Also famous for playing Jean Valjean", "First name rhymes with 'few'"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '8',
    categoryId: 'actors',
    question: "Who played Katniss Everdeen in The Hunger Games?",
    questions: ["Which actress became a symbol of female empowerment in YA films?", "Who won an Oscar for Silver Linings Playbook?"],
    answer: 'Jennifer Lawrence',
    answerType: 'single',
    hints: ["Known for being relatable and funny in interviews", "Last name is a type of saint"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '9',
    categoryId: 'movies',
    question: "What 1994 film features a man sitting on a bench telling his life story?",
    questions: ["Which movie had the famous line 'Run, Forrest, run!'?", "What Tom Hanks film won Best Picture?"],
    answer: 'Forrest Gump',
    answerType: 'single',
    hints: ["Features a man with a low IQ who experiences historical events", "Involves a box of chocolates"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '10',
    categoryId: 'movies',
    question: "What Christopher Nolan film explores dreams within dreams?",
    questions: ["Which movie features Leonardo DiCaprio as a thief who steals secrets?", "What film has a spinning top as a key object?"],
    answer: 'Inception',
    answerType: 'single',
    hints: ["Features multiple layers of reality", "The ending is famously ambiguous"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '11',
    categoryId: 'movies',
    question: "What 1999 film questions reality and features a red pill and blue pill?",
    questions: ["Which sci-fi film stars Keanu Reeves as a hacker?", "What movie features slow-motion bullet dodging?"],
    answer: 'The Matrix',
    answerType: 'single',
    hints: ["Features Agent Smith as the villain", "Revolutionized visual effects with 'bullet time'"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '12',
    categoryId: 'movies',
    question: "What Quentin Tarantino film features John Travolta and Samuel L. Jackson as hitmen?",
    questions: ["Which 1994 crime film has a non-linear narrative?", "What movie features the Royale with Cheese conversation?"],
    answer: 'Pulp Fiction',
    answerType: 'single',
    hints: ["Features a mysterious briefcase", "The dance scene at Jack Rabbit Slim's is iconic"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '13',
    categoryId: 'movies',
    question: "What James Cameron film became the highest-grossing movie of all time in 2009?",
    questions: ["Which film features blue aliens called the Na'vi?", "What movie is set on the planet Pandora?"],
    answer: 'Avatar',
    answerType: 'single',
    hints: ["Revolutionized 3D cinema technology", "Sequel was released in 2022"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '14',
    categoryId: 'movies',
    question: "What 1997 disaster film about a sinking ship won 11 Oscars?",
    questions: ["Which romantic film features 'I'm the king of the world!'?", "What movie has the song 'My Heart Will Go On'?"],
    answer: 'Titanic',
    answerType: 'single',
    hints: ["Stars Leonardo DiCaprio and Kate Winslet", "Based on a real historical disaster"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '15',
    categoryId: 'movies',
    question: "What Disney film features Elsa and Anna?",
    questions: ["Which animated movie has the song 'Let It Go'?", "What film is about a kingdom trapped in eternal winter?"],
    answer: 'Frozen',
    answerType: 'single',
    hints: ["Features a talking snowman named Olaf", "Set in the kingdom of Arendelle"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '16',
    categoryId: 'movies',
    question: "What 2008 Christopher Nolan Batman film features the Joker?",
    questions: ["Which Batman movie has Heath Ledger's final complete performance?", "What superhero film asks 'Why so serious?'"],
    answer: 'The Dark Knight',
    answerType: 'single',
    hints: ["Features Harvey Dent becoming Two-Face", "Widely considered one of the best superhero films"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '17',
    categoryId: 'musicians',
    question: "Who is the King of Pop?",
    questions: ["Who sang 'Thriller' and 'Billie Jean'?", "Which artist is known for the moonwalk?"],
    answer: 'Michael Jackson',
    answerType: 'single',
    hints: ["Started in The Jackson 5", "Known for his iconic white glove"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '18',
    categoryId: 'musicians',
    question: "Who is the Queen of Pop?",
    questions: ["Who sang 'Like a Virgin' and 'Vogue'?", "Which artist reinvented herself multiple times across decades?"],
    answer: 'Madonna',
    answerType: 'single',
    hints: ["Known for constant reinvention", "Single-name artist from the 80s"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '19',
    categoryId: 'musicians',
    question: "Who was the lead singer of Queen?",
    questions: ["Who sang 'Bohemian Rhapsody'?", "Which legendary frontman had a powerful four-octave vocal range?"],
    answer: 'Freddie Mercury',
    answerType: 'single',
    hints: ["Known for elaborate stage presence", "Born Farrokh Bulsara"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '20',
    categoryId: 'musicians',
    question: "Who is the lead singer of U2?",
    questions: ["Which Irish musician is known for activism and sunglasses?", "Who sang 'With or Without You'?"],
    answer: 'Bono',
    answerType: 'single',
    hints: ["Known for his humanitarian work", "Stage name is one word"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '21',
    categoryId: 'musicians',
    question: "Who was the lead singer of Nirvana?",
    questions: ["Who sang 'Smells Like Teen Spirit'?", "Which grunge icon tragically died in 1994?"],
    answer: 'Kurt Cobain',
    answerType: 'single',
    hints: ["Husband of Courtney Love", "First name sounds like 'curt'"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '22',
    categoryId: 'musicians',
    question: "Who is known as 'The Boss'?",
    questions: ["Who sang 'Born in the U.S.A.'?", "Which New Jersey rocker is known for working-class anthems?"],
    answer: 'Bruce Springsteen',
    answerType: 'single',
    hints: ["Leader of the E Street Band", "Known for marathon concerts"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '23',
    categoryId: 'musicians',
    question: "Who was the lead guitarist of The Beatles?",
    questions: ["Which Beatle was known as the 'Quiet One'?", "Who wrote 'While My Guitar Gently Weeps'?"],
    answer: 'George Harrison',
    answerType: 'single',
    hints: ["Known for his spiritual interests", "Was friends with Eric Clapton"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '24',
    categoryId: 'musicians',
    question: "Who is the lead singer of Foo Fighters?",
    questions: ["Who was the drummer for Nirvana?", "Which musician founded a band after Kurt Cobain's death?"],
    answer: 'Dave Grohl',
    answerType: 'single',
    hints: ["Known for being one of rock's nicest guys", "Played drums before becoming a frontman"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '25',
    categoryId: 'songs',
    question: "What Queen song starts with 'Is this the real life?'",
    questions: ["Which iconic rock opera is nearly 6 minutes long?", "What song has operatic and hard rock sections?"],
    answer: 'Bohemian Rhapsody',
    answerType: 'single',
    hints: ["Featured in Wayne's World", "No chorus structure"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '26',
    categoryId: 'songs',
    question: "What Beatles song mentions 'strawberry fields'?",
    questions: ["Which psychedelic Beatles track is about a Salvation Army children's home?", "What song was combined with 'Penny Lane' as a double A-side?"],
    answer: 'Strawberry Fields Forever',
    answerType: 'single',
    hints: ["Nothing is real in this song", "Features backward instruments"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '27',
    categoryId: 'songs',
    question: "What Nirvana song became an anthem of the 90s?",
    questions: ["Which grunge song starts with a famous guitar riff?", "What song includes the lyrics 'Here we are now, entertain us'?"],
    answer: 'Smells Like Teen Spirit',
    answerType: 'single',
    hints: ["Named after a deodorant brand", "From the album Nevermind"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '28',
    categoryId: 'songs',
    question: "What Led Zeppelin song is often called the greatest rock song ever?",
    questions: ["Which epic 8-minute rock song references a heavenly pathway?", "What song has the famous guitar solo by Jimmy Page?"],
    answer: 'Stairway to Heaven',
    answerType: 'single',
    hints: ["Builds from acoustic to electric", "Most requested song in radio history"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '29',
    categoryId: 'songs',
    question: "What Michael Jackson song features a horror-themed music video?",
    questions: ["Which song has a famous zombie dance?", "What was the bestselling album of all time's title track?"],
    answer: 'Thriller',
    answerType: 'single',
    hints: ["Features Vincent Price's voice", "14-minute music video directed by John Landis"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '30',
    categoryId: 'songs',
    question: "What Beatles song mentions being in an octopus's garden?",
    questions: ["Which underwater-themed Beatles song was written by Ringo?", "What whimsical song is about sea creatures?"],
    answer: "Octopus's Garden",
    answerType: 'single',
    hints: ["Sung by the drummer", "From Abbey Road"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '31',
    categoryId: 'songs',
    question: "What Eagles song is about a mysterious hotel?",
    questions: ["Which classic rock song mentions 'you can check out any time you like'?", "What song has an extended guitar solo at the end?"],
    answer: 'Hotel California',
    answerType: 'single',
    hints: ["Metaphor for excess in Southern California", "Features dual guitar solo"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '32',
    categoryId: 'songs',
    question: "What Beatles song did they perform on their first Ed Sullivan Show appearance?",
    questions: ["Which love song became their first #1 hit in America?", "What song mentions holding someone's hand?"],
    answer: 'I Want to Hold Your Hand',
    answerType: 'single',
    hints: ["Early Beatles song", "Simple title about physical affection"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '33',
    categoryId: 'albums',
    question: "What Pink Floyd album features a prism on the cover?",
    questions: ["Which 1973 album stayed on the charts for over 900 weeks?", "What concept album explores themes of time and money?"],
    answer: 'The Dark Side of the Moon',
    answerType: 'single',
    hints: ["One of the best-selling albums ever", "Features 'Money' and 'Time'"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '34',
    categoryId: 'albums',
    question: "What Nirvana album features a baby swimming underwater?",
    questions: ["Which 1991 album defined grunge music?", "What album features 'Smells Like Teen Spirit'?"],
    answer: 'Nevermind',
    answerType: 'single',
    hints: ["Controversial album cover", "Knocked Michael Jackson off #1"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '35',
    categoryId: 'albums',
    question: "What Beatles album features them crossing Abbey Road?",
    questions: ["Which Beatles album has the iconic zebra crossing photo?", "What was The Beatles' final recorded album?"],
    answer: 'Abbey Road',
    answerType: 'single',
    hints: ["Paul is barefoot on the cover", "Features 'Come Together' and 'Here Comes the Sun'"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '36',
    categoryId: 'albums',
    question: "What Michael Jackson album is the bestselling of all time?",
    questions: ["Which 1982 album features 'Billie Jean' and 'Beat It'?", "What album revolutionized music videos?"],
    answer: 'Thriller',
    answerType: 'single',
    hints: ["Produced by Quincy Jones", "Sold over 66 million copies"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '37',
    categoryId: 'albums',
    question: "What Fleetwood Mac album features 'Dreams' and 'Go Your Own Way'?",
    questions: ["Which 1977 album was made during relationship turmoil in the band?", "What album spent 31 weeks at #1?"],
    answer: 'Rumours',
    answerType: 'single',
    hints: ["Spelled the British way", "Created during band breakups"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '38',
    categoryId: 'albums',
    question: "What album features 'Stairway to Heaven'?",
    questions: ["Which Led Zeppelin album has no text on the cover?", "What 1971 album is referred to as Led Zeppelin IV?"],
    answer: 'Led Zeppelin IV',
    answerType: 'single',
    hints: ["Features four symbols representing band members", "Also contains 'Black Dog'"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '39',
    categoryId: 'albums',
    question: "What Radiohead album is often considered their masterpiece?",
    questions: ["Which 1997 album explores technology and alienation?", "What album features 'Karma Police' and 'No Surprises'?"],
    answer: 'OK Computer',
    answerType: 'single',
    hints: ["Named after a Hitchhiker's Guide to the Galaxy phrase", "Critically acclaimed art rock album"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '40',
    categoryId: 'albums',
    question: "What David Bowie album features Ziggy Stardust?",
    questions: ["Which 1972 concept album created Bowie's famous alter ego?", "What glam rock album features 'Starman'?"],
    answer: 'The Rise and Fall of Ziggy Stardust',
    answerType: 'single',
    hints: ["About an alien rock star", "Bowie's most famous persona"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '41',
    categoryId: 'cities',
    question: "What city is known as the Big Apple?",
    questions: ["Which American city has Times Square?", "What city never sleeps?"],
    answer: 'New York City',
    answerType: 'single',
    hints: ["Has boroughs including Manhattan and Brooklyn", "Features the Statue of Liberty"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '42',
    categoryId: 'cities',
    question: "What city is famous for the Eiffel Tower?",
    questions: ["Which French capital is called the City of Love?", "What city is known for fashion and croissants?"],
    answer: 'Paris',
    answerType: 'single',
    hints: ["Home to the Louvre", "On the Seine River"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '43',
    categoryId: 'cities',
    question: "What Japanese city is known for its ancient temples and geishas?",
    questions: ["Which city was Japan's capital for over 1000 years?", "What city features the famous bamboo grove?"],
    answer: 'Kyoto',
    answerType: 'single',
    hints: ["Name is an anagram of Tokyo", "Known for traditional tea ceremonies"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '44',
    categoryId: 'cities',
    question: "What Italian city is famous for its canals and gondolas?",
    questions: ["Which city has no roads, only waterways?", "What city sinks a few millimeters each year?"],
    answer: 'Venice',
    answerType: 'single',
    hints: ["Built on 118 small islands", "Known for annual carnival"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '45',
    categoryId: 'cities',
    question: "What city is home to Big Ben and Buckingham Palace?",
    questions: ["Which British capital is on the Thames River?", "What city was host to the 2012 Olympics?"],
    answer: 'London',
    answerType: 'single',
    hints: ["Known for double-decker buses", "Features Tower Bridge"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '46',
    categoryId: 'cities',
    question: "What Australian city has an iconic opera house?",
    questions: ["Which harbor city is known for its bridge and opera house?", "What city was host to the 2000 Olympics?"],
    answer: 'Sydney',
    answerType: 'single',
    hints: ["Features Bondi Beach", "Largest city in Australia"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '47',
    categoryId: 'cities',
    question: "What city is famous for its Space Needle?",
    questions: ["Which Pacific Northwest city is known for coffee culture?", "What city is home to Amazon and Microsoft?"],
    answer: 'Seattle',
    answerType: 'single',
    hints: ["Known for grunge music scene", "Very rainy climate"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '48',
    categoryId: 'cities',
    question: "What Brazilian city is famous for its carnival?",
    questions: ["Which city has the Christ the Redeemer statue?", "What city hosted the 2016 Olympics?"],
    answer: 'Rio de Janeiro',
    answerType: 'single',
    hints: ["Known for Copacabana beach", "Name means 'January River'"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '49',
    categoryId: 'restaurants',
    question: "What celebrity chef is known for saying 'BAM!'?",
    questions: ["Which chef is famous for Emeril's restaurants?", "Who brought Creole cuisine to national attention?"],
    answer: 'Emeril Lagasse',
    answerType: 'single',
    hints: ["Has restaurants in New Orleans", "Known for live cooking shows"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '50',
    categoryId: 'restaurants',
    question: "What Gordon Ramsay restaurant in London has three Michelin stars?",
    questions: ["Which fine dining establishment in Chelsea bears the chef's name?", "What restaurant is considered Ramsay's flagship?"],
    answer: 'Restaurant Gordon Ramsay',
    answerType: 'single',
    hints: ["Located on Royal Hospital Road", "Simply named after the chef"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '51',
    categoryId: 'restaurants',
    question: "What fast-food chain has golden arches?",
    questions: ["Which restaurant is known for Big Macs and Happy Meals?", "What chain says 'I'm lovin' it'?"],
    answer: "McDonald's",
    answerType: 'single',
    hints: ["Founded by Ray Kroc", "Most recognized fast-food brand globally"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '52',
    categoryId: 'restaurants',
    question: "What Chicago restaurant is famous for deep-dish pizza?",
    questions: ["Which pizzeria claims to have invented Chicago-style pizza?", "What restaurant opened in 1943 in River North?"],
    answer: 'Pizzeria Uno',
    answerType: 'single',
    hints: ["Number in the name", "The original location still operates"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '53',
    categoryId: 'streets',
    question: "What famous street in New York is known for theaters?",
    questions: ["Which street is synonymous with musical theater?", "What street runs through the Theater District?"],
    answer: 'Broadway',
    answerType: 'single',
    hints: ["Associated with musicals and shows", "Also refers to the theater industry itself"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '54',
    categoryId: 'streets',
    question: "What Los Angeles street is famous for celebrity homes?",
    questions: ["Which street curves through the Hollywood Hills?", "What street was the title of a David Lynch film?"],
    answer: 'Mulholland Drive',
    answerType: 'single',
    hints: ["Named after a Los Angeles engineer", "Offers views of the city"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '55',
    categoryId: 'streets',
    question: "What famous shopping street in London is known for department stores?",
    questions: ["Which street features Selfridges and John Lewis?", "What is London's premier shopping destination?"],
    answer: 'Oxford Street',
    answerType: 'single',
    hints: ["Named after a university town", "One of Europe's busiest shopping streets"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '56',
    categoryId: 'streets',
    question: "What San Francisco street is famous for its steep hills and cable cars?",
    questions: ["Which street zigzags down Russian Hill with eight sharp turns?", "What is called 'the most crooked street in the world'?"],
    answer: 'Lombard Street',
    answerType: 'single',
    hints: ["Brick-paved street with gardens", "Tourist attraction on Russian Hill"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '57',
    categoryId: 'clothing-brands',
    question: "What brand has a swoosh logo?",
    questions: ["Which athletic brand was named after a Greek goddess?", "What company was co-founded by Phil Knight?"],
    answer: 'Nike',
    answerType: 'single',
    hints: ["'Just Do It' slogan", "Headquartered in Oregon"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '58',
    categoryId: 'clothing-brands',
    question: "What brand has three stripes?",
    questions: ["Which German sportswear company competes with Nike?", "What brand makes Superstar sneakers?"],
    answer: 'Adidas',
    answerType: 'single',
    hints: ["Named after its founder Adolf Dassler", "Three parallel stripes logo"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '59',
    categoryId: 'clothing-brands',
    question: "What luxury Italian brand uses the double G logo?",
    questions: ["Which fashion house was founded by Guccio in Florence?", "What brand is known for its horsebit loafers?"],
    answer: 'Gucci',
    answerType: 'single',
    hints: ["Interlocking GG logo", "Known for maximalist designs"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '60',
    categoryId: 'clothing-brands',
    question: "What American denim brand has a red tab on the pocket?",
    questions: ["Which company invented blue jeans?", "What brand was founded by Levi Strauss?"],
    answer: "Levi's",
    answerType: 'single',
    hints: ["Associated with 501 jeans", "Founded during the Gold Rush era"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '61',
    categoryId: 'shoe-brands',
    question: "What brand is famous for Chuck Taylor All-Stars?",
    questions: ["Which sneaker brand has been popular since the 1920s?", "What shoe brand has a star logo?"],
    answer: 'Converse',
    answerType: 'single',
    hints: ["Basketball heritage", "Now owned by Nike"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '62',
    categoryId: 'shoe-brands',
    question: "What skateboarding shoe brand has a checkerboard pattern?",
    questions: ["Which brand has the slogan 'Off the Wall'?", "What shoe brand originated in California in 1966?"],
    answer: 'Vans',
    answerType: 'single',
    hints: ["Popular with skateboarders", "Known for canvas shoes"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '63',
    categoryId: 'shoe-brands',
    question: "What Italian luxury brand is known for its red-soled shoes?",
    questions: ["Which designer's shoes have signature red bottoms?", "What brand was founded by Christian in 1991?"],
    answer: 'Christian Louboutin',
    answerType: 'single',
    hints: ["Red lacquered soles", "Named after French designer"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '64',
    categoryId: 'shoe-brands',
    question: "What brand makes Air Jordans?",
    questions: ["Which company partnered with Michael Jordan?", "What brand dominates basketball shoe culture?"],
    answer: 'Nike',
    answerType: 'single',
    hints: ["Same brand as the swoosh", "Revolutionized athletic endorsements"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '65',
    categoryId: 'watch-brands',
    question: "What Swiss watch brand has a crown logo?",
    questions: ["Which luxury watch brand is associated with prestige and excellence?", "What brand makes the Submariner and Daytona?"],
    answer: 'Rolex',
    answerType: 'single',
    hints: ["Founded in 1905", "Synonymous with success"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '66',
    categoryId: 'watch-brands',
    question: "What watch brand uses the slogan 'You never actually own one'?",
    questions: ["Which Geneva-based brand is known for complications?", "What luxury brand says you 'merely look after it for the next generation'?"],
    answer: 'Patek Philippe',
    answerType: 'single',
    hints: ["One of the most expensive watch brands", "Founded in 1839"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '67',
    categoryId: 'watch-brands',
    question: "What brand created the first smartwatch?",
    questions: ["Which tech company revolutionized wearables in 2015?", "What brand makes watches that pair with iPhones?"],
    answer: 'Apple',
    answerType: 'single',
    hints: ["Known for the bitten apple logo", "Tech company from Cupertino"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '68',
    categoryId: 'watch-brands',
    question: "What Swiss brand is known for luxury watches and jewelry?",
    questions: ["Which brand uses the double C logo?", "What brand made the Tank watch?"],
    answer: 'Cartier',
    answerType: 'single',
    hints: ["French luxury brand", "Known for Love bracelets"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '69',
    categoryId: 'perfume-brands',
    question: "What French perfume house created No. 5?",
    questions: ["Which luxury brand's perfume was favored by Marilyn Monroe?", "What brand has interlocking C's?"],
    answer: 'Chanel',
    answerType: 'single',
    hints: ["Founded by Coco", "Iconic black and white branding"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '70',
    categoryId: 'perfume-brands',
    question: "What brand makes J'adore perfume?",
    questions: ["Which French luxury house was founded by Christian in 1946?", "What brand is known for the Lady Dior bag?"],
    answer: 'Dior',
    answerType: 'single',
    hints: ["Associated with haute couture", "Miss Dior is another famous fragrance"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '71',
    categoryId: 'perfume-brands',
    question: "What brand makes the fragrance Black Orchid?",
    questions: ["Which American designer's perfumes are known for bold scents?", "Who created fragrances like Tobacco Vanille?"],
    answer: 'Tom Ford',
    answerType: 'single',
    hints: ["Fashion designer turned filmmaker", "Known for sophisticated luxury"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '72',
    categoryId: 'perfume-brands',
    question: "What French brand makes La Vie Est Belle?",
    questions: ["Which luxury house was founded in 1935?", "What brand is known for Trésor perfume?"],
    answer: 'Lancôme',
    answerType: 'single',
    hints: ["Part of L'Oréal group", "Rose logo"],
    isCustom: false,
    difficulty: 'hard'
  },
  {
    id: '73',
    categoryId: 'luxury-brands',
    question: "What French brand is famous for its orange boxes?",
    questions: ["Which luxury brand started as a saddle maker?", "What brand makes Birkin and Kelly bags?"],
    answer: 'Hermès',
    answerType: 'single',
    hints: ["Founded in 1837", "Known for silk scarves"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '74',
    categoryId: 'luxury-brands',
    question: "What Italian brand uses a medusa head logo?",
    questions: ["Which fashion house was founded by Gianni in 1978?", "What brand is known for bold, colorful prints?"],
    answer: 'Versace',
    answerType: 'single',
    hints: ["Golden medusa symbol", "Headquarters in Milan"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '75',
    categoryId: 'luxury-brands',
    question: "What French brand has a monogram pattern with LV?",
    questions: ["Which trunk maker became a luxury fashion powerhouse?", "What brand makes the Speedy and Neverfull bags?"],
    answer: 'Louis Vuitton',
    answerType: 'single',
    hints: ["Part of LVMH group", "Brown monogram canvas is iconic"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '76',
    categoryId: 'luxury-brands',
    question: "What British brand is known for its checkered pattern?",
    questions: ["Which fashion house is famous for trench coats?", "What brand uses a knight on horseback logo?"],
    answer: 'Burberry',
    answerType: 'single',
    hints: ["Tan, black, red, and white check", "Founded in 1856"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '77',
    categoryId: 'musicians',
    question: "Who sang 'Rolling in the Deep'?",
    questions: ["Which British singer won multiple Grammys for '21'?", "Who made a comeback with '25' and '30' albums?"],
    answer: 'Adele',
    answerType: 'single',
    hints: ["Known for powerful ballads", "Albums named after her age"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '78',
    categoryId: 'musicians',
    question: "Who is known as 'The Voice'?",
    questions: ["Which diva sang 'I Will Always Love You'?", "Who starred in The Bodyguard?"],
    answer: 'Whitney Houston',
    answerType: 'single',
    hints: ["Daughter of Cissy Houston", "One of the best-selling music artists"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '79',
    categoryId: 'musicians',
    question: "Who was the lead singer of The Doors?",
    questions: ["Which rock poet sang 'Light My Fire'?", "Who is known as the Lizard King?"],
    answer: 'Jim Morrison',
    answerType: 'single',
    hints: ["Died at age 27", "Known for shamanic performances"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '80',
    categoryId: 'musicians',
    question: "Who sang 'Purple Rain'?",
    questions: ["Which Minneapolis artist was known for his unique style?", "Who performed at the Super Bowl halftime in the rain?"],
    answer: 'Prince',
    answerType: 'single',
    hints: ["Used a symbol as his name", "Multi-instrumentalist"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '81',
    categoryId: 'songs',
    question: "What Toto song is about a continent?",
    questions: ["Which 1982 hit mentions blessing the rains?", "What song features a distinctive keyboard intro?"],
    answer: 'Africa',
    answerType: 'single',
    hints: ["Internet meme favorite", "Chorus mentions blessing rains"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '82',
    categoryId: 'songs',
    question: "What Journey song is a karaoke favorite?",
    questions: ["Which power ballad mentions a small-town girl?", "What song says 'Don't stop believin''?"],
    answer: "Don't Stop Believin'",
    answerType: 'single',
    hints: ["Featured in The Sopranos finale", "About a journey on a midnight train"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '83',
    categoryId: 'songs',
    question: "What Bon Jovi song is about living on a prayer?",
    questions: ["Which 80s rock anthem features Tommy and Gina?", "What song says 'We're halfway there'?"],
    answer: "Livin' on a Prayer",
    answerType: 'single',
    hints: ["Released in 1986", "One of Bon Jovi's biggest hits"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '84',
    categoryId: 'songs',
    question: "What Beatles song mentions letting things be?",
    questions: ["Which Paul McCartney ballad was their final single?", "What song has 'speaking words of wisdom'?"],
    answer: 'Let It Be',
    answerType: 'single',
    hints: ["Inspired by a dream about his mother", "Title of their final album"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '85',
    categoryId: 'albums',
    question: "What U2 album features 'With or Without You'?",
    questions: ["Which 1987 album made U2 international superstars?", "What album has a stark black and white cover?"],
    answer: 'The Joshua Tree',
    answerType: 'single',
    hints: ["Named after a desert plant", "Also features 'Where the Streets Have No Name'"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '86',
    categoryId: 'albums',
    question: "What Prince album features 'When Doves Cry'?",
    questions: ["Which 1984 album was also a film?", "What album has songs named after colors?"],
    answer: 'Purple Rain',
    answerType: 'single',
    hints: ["Soundtrack to Prince's movie", "One of the best-selling albums ever"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '87',
    categoryId: 'albums',
    question: "What Metallica album is known as 'The Black Album'?",
    questions: ["Which 1991 album features 'Enter Sandman'?", "What self-titled Metallica album has a minimalist cover?"],
    answer: 'Metallica',
    answerType: 'single',
    hints: ["Plain black cover with snake logo", "Their best-selling album"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '88',
    categoryId: 'albums',
    question: "What Amy Winehouse album won five Grammys?",
    questions: ["Which 2006 album features 'Rehab'?", "What was Amy Winehouse's second and final studio album?"],
    answer: 'Back to Black',
    answerType: 'single',
    hints: ["Released just before her death", "Modern classic of soul music"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '89',
    categoryId: 'cities',
    question: "What city is known for its canals and bicycles?",
    questions: ["Which Dutch capital is famous for tulips?", "What city has the Anne Frank House?"],
    answer: 'Amsterdam',
    answerType: 'single',
    hints: ["More bikes than people", "Known for liberal policies"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '90',
    categoryId: 'cities',
    question: "What city is famous for its ancient Colosseum?",
    questions: ["Which Italian capital was once the center of an empire?", "What city has the Vatican within it?"],
    answer: 'Rome',
    answerType: 'single',
    hints: ["'The Eternal City'", "All roads lead to it"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '91',
    categoryId: 'actors',
    question: "Who played Captain Jack Sparrow?",
    questions: ["Which actor is known for quirky character choices?", "Who starred in Edward Scissorhands?"],
    answer: 'Johnny Depp',
    answerType: 'single',
    hints: ["Frequent Tim Burton collaborator", "Known for method acting"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '92',
    categoryId: 'actors',
    question: "Who played Neo in The Matrix?",
    questions: ["Which actor is known for John Wick?", "Who said 'Whoa' many times in the 90s?"],
    answer: 'Keanu Reeves',
    answerType: 'single',
    hints: ["Known for being humble and kind", "Canadian actor"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '93',
    categoryId: 'movies',
    question: "What Steven Spielberg film features a shark terrorizing a beach town?",
    questions: ["Which 1975 thriller made people afraid of the ocean?", "What movie has the line 'You're gonna need a bigger boat'?"],
    answer: 'Jaws',
    answerType: 'single',
    hints: ["Filmed in Martha's Vineyard", "Iconic theme music by John Williams"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '94',
    categoryId: 'movies',
    question: "What film features a young boy who sees dead people?",
    questions: ["Which M. Night Shyamalan film has a twist ending?", "What movie has the line 'I see dead people'?"],
    answer: 'The Sixth Sense',
    answerType: 'single',
    hints: ["Stars Bruce Willis", "The ending recontextualizes everything"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '95',
    categoryId: 'songs',
    question: "What song by The Police is about obsessive love?",
    questions: ["Which 1983 hit is often misunderstood as romantic?", "What song says 'Every breath you take'?"],
    answer: 'Every Breath You Take',
    answerType: 'single',
    hints: ["Actually about stalking", "Most popular at weddings despite dark meaning"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '96',
    categoryId: 'songs',
    question: "What Fleetwood Mac song is about a Welsh witch?",
    questions: ["Which mystical song was written by Stevie Nicks?", "What song mentions women and thunder?"],
    answer: 'Rhiannon',
    answerType: 'single',
    hints: ["From the album Fleetwood Mac (1975)", "Based on Welsh mythology"],
    isCustom: false,
    difficulty: 'medium'
  },
  {
    id: '97',
    categoryId: 'albums',
    question: "What Adele album features 'Someone Like You'?",
    questions: ["Which album is titled after her age in 2011?", "What album won Album of the Year at the Grammys?"],
    answer: '21',
    answerType: 'single',
    hints: ["Her second studio album", "Best-selling album of 2011 and 2012"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '98',
    categoryId: 'cities',
    question: "What city is known for its ancient pyramids?",
    questions: ["Which Egyptian capital is near the Giza complex?", "What city sits on the Nile River?"],
    answer: 'Cairo',
    answerType: 'single',
    hints: ["Largest city in the Arab world", "Home to the Egyptian Museum"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '99',
    categoryId: 'movies',
    question: "What Pixar film is about a rat who wants to be a chef?",
    questions: ["Which animated film is set in Paris?", "What movie has the tagline 'Anyone can cook'?"],
    answer: 'Ratatouille',
    answerType: 'single',
    hints: ["Features a rat named Remy", "Title is a French dish"],
    isCustom: false,
    difficulty: 'easy'
  },
  {
    id: '100',
    categoryId: 'musicians',
    question: "Who is known as 'The Piano Man'?",
    questions: ["Who sang 'Uptown Girl' and 'We Didn't Start the Fire'?", "Which singer-songwriter has sold over 150 million records?"],
    answer: 'Billy Joel',
    answerType: 'single',
    hints: ["From New York", "Known for storytelling songs"],
    isCustom: false,
    difficulty: 'easy'
  }
];
